### ISSUE TITLE
Error: SGDEX, please implement 'GetSceneName() as String' function and return name of your scene that is extended from BaseScene

### ISSUE THREAD

**Issue by IanWONeill** [lvcabral/brs-emu#109]
[roku-deploy (1) (1).zip](https://github.com/lvcabral/brs-emu/files/9410359/roku-deploy.1.1.zip)

**Comment by lvcabral** [comment]
SceneGraph is out of scope for now, please read: https://github.com/lvcabral/brs-emu/blob/master/docs/limitations.md
