### ISSUE TITLE
BRS runtime error: source/main.brs(69,29-30): 'setMessagePort' is not a function and cannot be called.

### ISSUE THREAD

**Issue by IanWONeill** [lvcabral/brs-emu#110]
[IPTVSmartersProRokuApp_3.0.0-ToSmartUsers.zip](https://github.com/lvcabral/brs-emu/files/9410364/IPTVSmartersProRokuApp_3.0.0-ToSmartUsers.zip)

**Comment by ShriprasadM** [comment]
@lvcabral  any updates here? I have used https://github.com/lvcabral/brs-emu/releases/tag/v0.9.0-emu but still same issue
