### ISSUE TITLE
Implement missing `roDeviceInfo` methods up to Roku OS 10.0

### ISSUE THREAD

**Issue by lvcabral** [lvcabral/brs-emu#134]
https://developer.roku.com/en-gb/docs/references/brightscript/interfaces/ifdeviceinfo.md

- roDeviceInfo.getOSVersion()
- roDeviceInfo.getDrmInfoEx()
- roDeviceInfo.canDecodeAudio()
- roDeviceInfo.getAudioOutputChannel()
- roDeviceInfo.canDecodeVideo()
- roDeviceInfo.enableCodecCapChangedEvent()
- roDeviceInfo.IsAudioGuideEnabled()
- roDeviceInfo.getConnectionInfo()
- roDeviceInfo.isStoreDemoMode()
- roDeviceInfo.getPreferredCaptionLanguage()
- roDeviceInfo.enableInternetStatusEvent()
- roDeviceInfo.forceInternetStatusCheck()

**Comment by upintheairsheep** [comment]
By the way, you might be interested in touchHLE ( https://github.com/hikari-no-yume/touchHLE ), which basically is just like this project but for legacy iOS apps, you could take inspiration from it or try collab.
