### ISSUE TITLE
Remove browser gateway altogether 

### ISSUE THREAD

**Issue by upintheairsheep** [lvcabral/brs-emu#145]
The browser is not supported error is annoying and almost useless, you really should remove the check altogether, it isn’t necessary at all, only an unfair gateway, only put a note that the browser is untested.

**Comment by upintheairsheep** [comment]
By the way, an anonymous donor donated a dump of the Roku OS system files: https://archive.org/download/roku_disk_image/roku_disk_image.zip/
The plug-ins folder has a few Roku apps, and that includes the Home Screen itself

**Comment by upintheairsheep** [comment]
Download: https://archive.org/download/roku_disk_image/roku_disk_image.zip

**Comment by lvcabral** [comment]
Now that even Safari supports it, I will remove, good point.
This dump is cool, will take a look.

**Comment by lvcabral** [comment]
Addressed on #181
