### ISSUE TITLE
Clear canvas when value is 0

### ISSUE THREAD

**Issue by Matt-Moores** [lvcabral/brs-emu#158]
Canvas is not cleared if value is 0
```js
clearCanvas(rgba: number) {
  const ctx = this.context;
  ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
  if ((rgba & 255) > 0) {
      ctx.fillStyle = rgbaIntToHex(rgba);
      ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);
  }
  this.rgbaRedraw = true;
  return BrsInvalid.Instance;
}
```

Should this be `if ((rgba & 255) >= 0) {`

**Comment by lvcabral** [comment]
The behavior is actually correct, as Roku does use the alpha on the destination, not the source. 
The following code works on both the emulator and a Roku device the same way:
```brs
Function Main()
    s=CreateObject("roScreen", true, 1280, 720)
    ' Clear to White with alpha fully opaque
    ' but alpha not actually ever used since it is the bottom most plane
    ' alpha is only looked at on "source" planes, not "destination".
    s.Clear(&hFFFFFFFF)
    ' AlphaEnable must be enabled in the destination surface to have effect.
    s.SetAlphaEnable(true)
    bm=CreateObject("roBitmap", {width:450, height: 450, alphaenable: true} )
    bm.Clear(0) 'black, transparent when alpha is true
    s.DrawObject(450, 150, bm)
    s.swapBuffers()
    ' redraw with the alpha disabled, black square is shown
    Sleep(5000)
    s.Clear(&hFFFFFFFF)
    s.SetAlphaEnable(false)
    s.DrawObject(450, 150, bm)
    s.swapBuffers()
    Sleep(5000)
End Function
```
Run this code on [brsFilddle](https://brsfiddle.net/?code=XQAAAAIRAwAAAAAAAABJKocHE2PYgsXwYH9wkZq58wTONZVmZIi586pP5_r9kdUes_tacAU5p7mT2FjxIsvfvna05Tkhy3JTiiU2XYH-zC3PDgZeIOJYpmIegY7AEGfOLTjjy6IssiXrakEsU9q0qLww391KC8o8C1wtigfj94IlkAyHgAi7I8taq1fO4x2k4dDAoxy66BNW_Nhp-ncvZvYvOFMWwROb_rY5Ga5Jn-4fc2OZvMIi28Vk6oZDSup5PgiqpnmZFC5PKIWrEh0ReZYC6HaxjVYKifyll_Xzc8vO1GGDBfNfvJNRtLiogshLkosGcqJ-kRK0OjKUOJy6KGWgJFlWQuj3g1RJYDiRb9wzQqfWu5ueg32k2_lDDbd5AowC8nqmRvqws-RQuUfAyXmyrxl0pQih-y9zK5TP_UnFCMN1OJmZkCwh4dHwfJFlAP6YMRagPZopXoxwPu2KEmF96VGMtEzODn79qoQQLE_vQg3EBWRcwXDp7DOO3XKMY8tQFjsm8geCj1-AcMC7o8PZHDB59LQSuzGyehT1YlmXoRswIxwKkjp84u_N0hLeA7gNuecEixaSP_-HsDuA)
