### ISSUE TITLE
Issue: setMessagePort is not function

### ISSUE THREAD

**Issue by ShriprasadM** [lvcabral/brs-emu#177]
<img width="1111" alt="image" src="https://github.com/lvcabral/brs-emu/assets/9314645/712a064f-118f-4187-aee2-97f5c49c977f">

> setMessagePort is not a function.

I have used following example, but even facing same issues with other examples too.

https://github.com/googleads/googleads-ima-roku-dai/tree/main/podserving_example

**Comment by lvcabral** [comment]
This example uses SceneGraph and as stated on Readme and the limitations documentation, the emulator still do not support RSG components
