### ISSUE TITLE
Implement RAF mock objects

### ISSUE THREAD

**Issue by lvcabral** [lvcabral/brs-emu#25]
https://developer.roku.com/en-gb/docs/developer-program/advertising/raf-api.md
https://developer.roku.com/en-gb/docs/developer-program/advertising/integrating-roku-advertising-framework.md

**Comment by Matt-Moores** [comment]
At least add 'Library "Roku_Ads.brs"' to be a valid lbrary

**Comment by lvcabral** [comment]
> At least add 'Library "Roku_Ads.brs"' to be a valid lbrary

This will be included on the next release (v0.4.0)

**Comment by lvcabral** [comment]
Reopening to add more methods and fix showAds() to return true
