### ISSUE TITLE
using ":" to have multiple statement on one line "Found unexpected token ':'"

### ISSUE THREAD

**Issue by Matt-Moores** [lvcabral/brs-emu#38]

**Comment by lvcabral** [comment]
Hi Matt, thanks for reporting the issue! Issues related to the language interpreter please report to the original project sjbarag/brs, as I'm integrating all improvements from there to my fork. I am also pushing back improvements I make. So here I only open issues related to the components that will never be ported back to `BRS` or I have a different implementation.
