### ISSUE TITLE
Add support for Conditional Compilation

### ISSUE THREAD

**Issue by Clauvin** [lvcabral/brs-emu#93]
**A description of the new or missing feature:** https://developer.roku.com/pt-br/docs/references/brightscript/language/conditional-compilation.md

**A sample BrightScript file that uses the feature:** none, sorry :/ Once I have a Roku with me, will be able to create one and then link here.

**Link to the BrightScript documentation describing its behavior:** As above, https://developer.roku.com/pt-br/docs/references/brightscript/language/conditional-compilation.md

**Comment by lvcabral** [comment]
I know the BRS project is working on this implementation, I will integrate as soon as it is ready there.

**Comment by Clauvin** [comment]
Thanks :)

**Comment by lvcabral** [comment]
Implementation was properly activated and merged, to be available in next release.
