### ISSUE TITLE
Unable to install Roku Sample Channels for Automated Channel Testing

### ISSUE THREAD

**Issue by ilyas1996** [lvcabral/brs-emu#99]
**Environment:**
Windows 10
BrightScript Emulator - 0.9.0
Node - 12.14.1
Chrome - 83

**Issue:**

- I am trying to automate few Sample Channels provided by Roku - Automated Channel Testing Tools

- While I am Installing the sample channels in the Emulator , i am able to see the first page "Roku Developers" and after few seconds it became blank.

- Is this emulator is only work for games that you have provided or else we can able to install any Roku channels?

Please find Roku Automated Testing Tool:
https://github.com/rokudev/automated-channel-testing

Please find below sample channels:
[channel.zip](https://github.com/lvcabral/brs-emu/files/7370881/channel.zip)
[9_Bookmarks.zip](https://github.com/lvcabral/brs-emu/files/7370887/9_Bookmarks.zip)

**Comment by lvcabral** [comment]
The emulator currently do not support SceneGraph only regular BrightScript and the Draw 2D API objects, please read the limitations document: https://github.com/lvcabral/brs-emu/blob/master/docs/limitations.md
